function gui()

    Font = 10;
    %create and construct GUI well hidden%
    gui = figure('Name', 'PetPal', 'Position', [600, 600, 350, 150]', ...
        'Toolbar', 'none' , 'MenuBar', 'none', 'NumberTitle', 'off');

    %buttons that decide if user is owner or sitter
    owner = uicontrol(gui, 'Style', 'pushbutton', ...
    'String', 'Pet Owner', ...
    'Position', [60, 70, 100, 30], ...
    'FontSize', Font);

    sitter = uicontrol(gui, 'Style', 'pushbutton', ...
    'String', 'Pet Sitter', ...
    'Position', [180, 70, 100, 30], ...
    'FontSize', Font);

    %button is clicked if owner udate to owner gui if sitter switch to sitter gui 
    set(owner, 'Callback', {@PetOwner, gui, owner, sitter, Font});
    set(sitter, 'Callback', {@PetSitter, gui ,owner, sitter, Font});
end
