function Pet(~,~, gui, ownerInfo)
    % Delete all children of the GUI
    delete(get(gui, 'Children'));

    set(gui, 'Units', 'normalized', 'Position', [0.2, .2, .5, .3]);

    PetInfo = uicontrol(gui, 'Style', 'text', ...
        'String', 'Pet Information', ...
        'Units', 'normalized', ...
        'Position', [0.25, .825, 0.5, 0.1], 'FontSize', 18 );

    PetNameLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'Pet Name:', ...
        'Units', 'normalized', ...
        'Position', [0.02, .675, 0.1, 0.1]);
    PetName = uicontrol(gui, "Style", "edit", ...
        'Units', 'normalized', ...
        "Position", [.12, .7, 0.14, 0.1]);

    PetBreedLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'Pet Breed:', ...
        'Units', 'normalized', ...
        'Position', [0.26, .675, 0.1, 0.1]);
    PetBreed = uicontrol(gui, "Style", "edit", ...
        'Units', 'normalized', ...
        "Position", [.36, .7, 0.14, 0.1]);

    PetAgeLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'Pet Age:', ...
        'Units', 'normalized', ...
        'Position', [0.50, .675, 0.08, 0.1]);
    PetAge = uicontrol(gui, "Style", "edit", ...
        'Units', 'normalized', ...
        "Position", [.57, .7, 0.14, 0.1]);

    PetBehaviorLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'Pet Behaviour:', ...
        'Units', 'normalized', ...
        'Position', [0.72, .675, 0.1, 0.1]);
    PetBehaviour = uicontrol(gui, "Style", "edit", ...
        'Units', 'normalized', ...
        "Position", [.82, .7, 0.14, 0.1]);

    %Next Line%

    PetGenderLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'Pet Gender:', ...
        'Units', 'normalized', ...
        'Position', [0.02, .475, 0.1, 0.1]);
    PetGender = uicontrol(gui, "Style", "edit", ...
        'Units', 'normalized', ...
        "Position", [.12, .5, 0.14, 0.1]);

    PetInstructionsLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'Special Instructons:', ...
        'Units', 'normalized', ...
        'Position', [0.26, .475, 0.2, 0.1]);
    PetInstructions = uicontrol(gui, "Style", "edit", ...
        'Units', 'normalized', ...
        "Position", [.45, .45, 0.28, 0.2]);


submit = uicontrol(gui, 'Style', 'pushbutton', ...
        'String', 'submit', ...
        'Units', 'normalized', ...
        'Position', [.25, .2, .25, .2], ...
        'FontSize', 16);
    set(submit, 'Callback', {@PetSave, gui, ownerInfo, PetName, PetBreed, PetAge, PetBehaviour, PetGender, PetInstructions });

end