function PetOwner(~, ~, gui, owner, sitter)
    delete(owner);
    delete(sitter)
    set(gui, 'position', [400, 100, 900, 600]);
    
    %Name%
    NameLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'Name:', ...
        'Position', [50, 500, 50, 20]);
    Name = uicontrol(gui, "Style", "edit", ...
        "Position", [100, 500, 100, 30]);
    
    %Age%
    AgeLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'Age:', ...
        'Position', [200, 500, 50, 20]);
    Age = uicontrol(gui, "Style", "edit", ...
        "Position", [250, 500, 100, 30]);

    %Address%
    AddressLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'Address:', ...
        'Position', [360, 500, 50, 20]);
    Address = uicontrol(gui, "Style", "edit", ...
        "Position", [420, 500, 100, 30]);
    
    %City% 
    CityLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'City:', ...
        'Position', [520, 500, 50, 20]);
    City = uicontrol(gui, "Style", "edit", ...
        "Position", [570, 500, 100, 30]);

    %Province/state%
    provinceLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'Province:', ...
        'Position', [690, 500, 50, 20]);
    Province = uicontrol(gui, "Style", "edit", ...
        "Position", [750, 500, 100, 30]);


end 