function PetOwner(~, ~, gui, owner, sitter, Font)
    delete(owner);
    delete(sitter)
    set(gui, 'Units', 'normalized', 'Position', [0.2, .2, .5, .3]);
    
    %Name%
    NameLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'Name:', ...
        'Units', 'normalized', ...
        'Position', [0.01, .775, 0.05, 0.1]);
    Name = uicontrol(gui, "Style", "edit", ...
        'Units', 'normalized', ...
        "Position", [.06, .8, 0.14, 0.1]);
    
    %Age%
    AgeLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'Age:', ...
        'Units', 'normalized', ...
        'Position', [0.2, .775, 0.05, 0.1]);
    Age = uicontrol(gui, "Style", "edit", ...
        'Units', 'normalized', ...
        "Position", [.25, .8, 0.14, 0.1]);

    %Address%
    AddressLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'Address:', ...
        'Units', 'normalized', ...
        'Position', [0.4, .775, 0.05, 0.1]);
    Address = uicontrol(gui, "Style", "edit", ...
        'Units', 'normalized', ...
        "Position", [.45, .8, 0.14, 0.1]);
    
    %City% 
    CityLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'City:', ...
        'Units', 'normalized', ...
        'Position', [0.6, .775, 0.05, 0.1]);
    City = uicontrol(gui, "Style", "edit", ...
        'Units', 'normalized', ...
        "Position", [.65, .8, 0.14, 0.1]);

    %Province/state%
    provinceLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'Province:', ...
        'Units', 'normalized', ...
        'Position', [0.8, .775, 0.05, 0.1]);
    Province = uicontrol(gui, "Style", "edit", ...
        'Units', 'normalized', ...
        "Position", [.85, .8, 0.14, 0.1]);
    
%Next Line%
    
    %country 
    CountryLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'Country:', ...
        'Units', 'normalized', ...
        'Position', [0.01, .63, 0.05, 0.1]);
    Country = uicontrol(gui, "Style", "edit", ...
        'Units', 'normalized', ...
        "Position", [.06, .65, 0.14, 0.1]);

    %phone Number%
    PhoneNumberLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'Phone Number:', ...
        'Units', 'normalized', ...
        'Position', [0.2, .63, 0.1, 0.1]);
    PhoneNumber = uicontrol(gui, "Style", "edit", ...
        'Units', 'normalized', ...
        "Position", [.3, .65, 0.14, 0.1]);

%Buttons%
    
    Back = uicontrol(gui, 'Style', 'pushbutton', ...
        'String', 'Back', ...
        'Units', 'normalized', ...
        'Position', [.25, .25, .25, .25], ...
        'FontSize', Font);
    set(Back, 'Callback', {@Goback, gui});

    submit = uicontrol(gui, 'Style', 'pushbutton', ...
        'String', 'submit', ...
        'Units', 'normalized', ...
        'Position', [.55, .25, .25, .25], ...
        'FontSize', Font);
    set(submit, 'Callback', {@OwnerSave, gui, Name, Age, Address, City, Province, Country, PhoneNumber});

    

end 