function PetOwner(~, ~, gui, owner, sitter, Font)
    delete(owner);
    delete(sitter)
    set(gui, 'Units', 'normalized', 'Position', [0.2, .2, .5, .3]);
    
    OwnerInfo= uicontrol(gui, 'Style', 'text', ...
        'String', 'Owner Information', ...
        'Units', 'normalized', ...
        'Position', [0.25, .825, 0.5, 0.1], 'FontSize', 16);

    %Name%
    NameLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'Name:', ...
        'Units', 'normalized', ...
        'Position', [0.01, .675, 0.05, 0.1]);
    Name = uicontrol(gui, "Style", "edit", ...
        'Units', 'normalized', ...
        "Position", [.06, .7, 0.14, 0.1]);
    
    %Age%
    AgeLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'Age:', ...
        'Units', 'normalized', ...
        'Position', [0.2, .675, 0.05, 0.1]);
    Age = uicontrol(gui, "Style", "edit", ...
        'Units', 'normalized', ...
        "Position", [.25, .7, 0.14, 0.1]);

    %Address%
    AddressLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'Address:', ...
        'Units', 'normalized', ...
        'Position', [0.4, .675, 0.06, 0.1]);
    Address = uicontrol(gui, "Style", "edit", ...
        'Units', 'normalized', ...
        "Position", [.46, .7, 0.14, 0.1]);
    
    %City% 
    CityLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'City:', ...
        'Units', 'normalized', ...
        'Position', [0.6, .675, 0.05, 0.1]);
    City = uicontrol(gui, "Style", "edit", ...
        'Units', 'normalized', ...
        "Position", [.65, .7, 0.14, 0.1]);


%Next Line%

    %Province/state%
    provinceLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'Province:', ...
        'Units', 'normalized', ...
        'Position', [0.01, .53, 0.07, 0.1]);
    Province = uicontrol(gui, "Style", "edit", ...
        'Units', 'normalized', ...
        "Position", [.08, .55, 0.14, 0.1]);
    
    %country 
    CountryLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'Country:', ...
        'Units', 'normalized', ...
        'Position', [0.22, .53, 0.07, 0.1]);
    Country = uicontrol(gui, "Style", "edit", ...
        'Units', 'normalized', ...
        "Position", [.29, .55, 0.14, 0.1]);

    %phone Number%
    PhoneNumberLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'Phone Number:', ...
        'Units', 'normalized', ...
        'Position', [0.43, .53, 0.15, 0.1]);
    PhoneNumber = uicontrol(gui, "Style", "edit", ...
        'Units', 'normalized', ...
        "Position", [.58, .55, 0.14, 0.1]);

%Buttons%

    submit = uicontrol(gui, 'Style', 'pushbutton', ...
        'String', 'submit', ...
        'Units', 'normalized', ...
        'Position', [.25, .25, .25, .25], ...
        'FontSize', Font);
    set(submit, 'Callback', {@OwnerSave, gui, Name, Age, Address, City, Province, Country, PhoneNumber});

    

end 