function PetSitter(~, ~, gui, owner, sitter, Font)
    delete(owner);
    delete(sitter)
    set(gui, 'Units', 'normalized', 'Position', [0.2, .2, .5, .3]);

    SitterInfo= uicontrol(gui, 'Style', 'text', ...
        'String', 'Pet Sitter Information', ...
        'Units', 'normalized', ...
        'Position', [0.25, .825, .5, 0.1], 'FontSize', 16);

    %Name%
    NameLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'Name:', ...
        'Units', 'normalized', ...
        'Position', [0.02, .675, 0.05, 0.1]);
    Name = uicontrol(gui, "Style", "edit", ...
        'Units', 'normalized', ...
        "Position", [.07, .7, 0.14, 0.1]);
    
    %Age%
    AgeLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'Age:', ...
        'Units', 'normalized', ...
        'Position', [0.21, .675, 0.05, 0.1]);
    Age = uicontrol(gui, "Style", "edit", ...
        'Units', 'normalized', ...
        "Position", [.26, .7, 0.14, 0.1]);

    %Address%
    AddressLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'Address:', ...
        'Units', 'normalized', ...
        'Position', [0.4, .675, 0.06, 0.1]);
    Address = uicontrol(gui, "Style", "edit", ...
        'Units', 'normalized', ...
        "Position", [.46, .7, 0.14, 0.1]);
    
    %City% 
    CityLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'City:', ...
        'Units', 'normalized', ...
        'Position', [0.6, .675, 0.05, 0.1]);
    City = uicontrol(gui, "Style", "edit", ...
        'Units', 'normalized', ...
        "Position", [.65, .7, 0.14, 0.1]);


%Next Line%

    %Province/state%
    provinceLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'Province:', ...
        'Units', 'normalized', ...
        'Position', [0.02, .53, 0.07, 0.1]);
    Province = uicontrol(gui, "Style", "edit", ...
        'Units', 'normalized', ...
        "Position", [.09, .55, 0.14, 0.1]);
    
    %country 
    CountryLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'Country:', ...
        'Units', 'normalized', ...
        'Position', [0.23, .53, 0.07, 0.1]);
    Country = uicontrol(gui, "Style", "edit", ...
        'Units', 'normalized', ...
        "Position", [.30, .55, 0.14, 0.1]);

    %phone Number%
    PhoneNumberLabel = uicontrol(gui, 'Style', 'text', ...
        'String', 'Phone Number:', ...
        'Units', 'normalized', ...
        'Position', [0.44, .53, 0.15, 0.1]);
    PhoneNumber = uicontrol(gui, "Style", "edit", ...
        'Units', 'normalized', ...
        "Position", [.58, .55, 0.14, 0.1]);

    Next = uicontrol(gui, 'Style', 'pushbutton', ...
        'String', 'Next', ...
        'Units', 'normalized', ...
        'Position', [.25, .2, .25, .2], ...
        'FontSize', 16);
    set(submit, 'Callback', {@SitterSave, gui, Name, Age, Address, City, Province, Country, PhoneNumber });


    
end